// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8D7g1WNkA4cxb5zWd0CAS9DQhVtFKv5c',
    appId: '1:287727538614:web:5e4f64f3b6e0a10d963117',
    messagingSenderId: '287727538614',
    projectId: 'worldchat-fc10f',
    authDomain: 'worldchat-fc10f.firebaseapp.com',
    storageBucket: 'worldchat-fc10f.appspot.com',
    measurementId: 'G-G8BB26DECD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgEAx8oDgWFsbAkkdtClNP-VnVh_KyNG0',
    appId: '1:287727538614:android:de5281c5d4037d77963117',
    messagingSenderId: '287727538614',
    projectId: 'worldchat-fc10f',
    storageBucket: 'worldchat-fc10f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJuBLguPpwBP6Nn4K718FWki7sMlAmscs',
    appId: '1:287727538614:ios:de9e2aca32d6795c963117',
    messagingSenderId: '287727538614',
    projectId: 'worldchat-fc10f',
    storageBucket: 'worldchat-fc10f.appspot.com',
    iosBundleId: 'com.example.worldchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJuBLguPpwBP6Nn4K718FWki7sMlAmscs',
    appId: '1:287727538614:ios:a09f09086b7e5ed1963117',
    messagingSenderId: '287727538614',
    projectId: 'worldchat-fc10f',
    storageBucket: 'worldchat-fc10f.appspot.com',
    iosBundleId: 'com.example.worldchat.RunnerTests',
  );
}
